version: "2"

services:
  elasticsearch:
    image: elasticsearch:6.5.2
    hostname: elasticsearch
    container_name: curbside-onyx-elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
