version: "2"

services:
  elasticsearch:
    image: elasticsearch:6.5.2
    hostname: elasticsearch
    container_name: curbside-onyx-elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.2
    container_name: curbside-onyx-kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
